copy:   # Main Command
  perm: copybook.use
  usage: "&cUse: &7/stampante"
  hold: "&cYou have to hold a book"
  noperm: "&cYou Don't have enough perms to copy books"
  success: "&aBook Copied"
  amount: 1   # How many copies
  actionbar: "&aCopying your book..."
  delay: 5  # Time Delay (( In Seconds ))


item-allow:  # Item that can be copied
  item1: WRITABLE_BOOK
  item2: WRITTEN_BOOK

admin:   # Reload Command
  perm: copybook.admin
  usage: "&cUse: &7/ca reload"
  reload: "&aConfig Reloaded with success"
  noperm: "&cYou don't have enough perms to use this command"