copy:   # Comando principale
  perm: outcopy.copybook  # Permesso per fotocopiare
  usage: "&cUsa: &7/stampante"
  hold: "&cDevi tenere in mano il libro da stampare"
  noperm: "&cNon hai abbastanza permessi per stampare libri"
  success: "&aLibro fotocopiato"
  amount: 1   # Quante copie darà al player
  actionbar: "&aSto stampando il tuo libro..."
  delay: 5  # In quanti secondi si stampa il libro (( in secondi ))


item-allow:  # Item che si possono fotocopiare (( Suggerisco di lasciarli così ovviamente ))
  item1: WRITABLE_BOOK
  item2: WRITTEN_BOOK

admin:   # Comando per reloddare il config
  perm: outcopy.admin
  usage: "&cUsa: &7/ca reload"
  reload: "&aConfig ricaricato con successo"
  noperm: "&cNon hai abbastanza permessi per eseguire questo comando"